-- AlterTable
ALTER TABLE "GameSettings" ADD COLUMN     "cooldownMs" INTEGER NOT NULL DEFAULT 60000,
ADD COLUMN     "maxSkips" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "skipPenalty" INTEGER NOT NULL DEFAULT 5;
